// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqcoufrbfgqfbxxyylnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxY291ZnJiZmdxZmJ4eHl5bG53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDM1ODIsImV4cCI6MjA2NzIxOTU4Mn0.yaN7btuTeS0RdOw2LHFaEkS2OHrq5DwgtQjUMmgEwJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});